### ISSUE TITLE
Tripwire fills the disk buffer cache when checking

### ISSUE THREAD

**Issue by sbrl** [Tripwire/tripwire-open-source#2]
If I run tripwire on my server, it causes my disk buffer cache to fill up, which pushes legitimate applications out of RAM and into the swap space.

An option in to bypass the disk buffer cache would be welcome, as it would allow me to use tripwire on my server without grinding it to a halt.

**Comment by brc0x1** [comment]
I don't have an ETA on this issue, but do I have a couple of possible approaches in mind:

* Linux (and IIRC FreeBSD) have a posix_fadvise() syscall that lets the client explain how it plans to use a file descriptor, so the kernel can tweak disk caching accordingly.  Both the POSIX_FADV_SEQUENTIAL and POSIX_FADV_DONTNEED seem appropriate for our use; apparently you can't combine the two, though, and I'm not sure which (if either) would deliver better results.
 
* Or we could just open files with some combination of O_DIRECT and/or O_SYNC, to just bypass disk caching entirely.  If this turned out to be the best approach, it would probably end up as a new optional tw.cfg parameter, disabled by default.

**Comment by sbrl** [comment]
I'd be willing to test a few builds against my (rather strange) VPS if that's
helpful.

**Comment by brc0x1** [comment]
In case you're interested, my work-in-progress branch is here: https://github.com/brc0x1/tripwire-open-source.  It issues a posix_fadvise(POSIX_FADV_SEQUENTIAL) on opening a file, and a posix_fadvise(POSIX_FADV_DONTNEED) right before closing it.  That should kick files out of the disk cache after we're done with them.

There's also a DIRECT_IO tw.cfg param, but I wouldn't advise using it right now.  I haven't implemented aligning the read buffer on a page boundary yet (which O_DIRECT requires), so hashing a file currently fails whenever that condition doesn't hold.

**Comment by brc0x1** [comment]
Ok, I have a new pull request up that includes the cache hinting and direct i/o stuff:  https://github.com/Tripwire/tripwire-open-source/pull/10 .  The optional config param I mentioned is renamed HASH_DIRECT_IO for clarity, since it's only used while generating hashes, and not for accessing OST key/config/policy/db/report files.

**Comment by brc0x1** [comment]
The tweaks & features mentioned in the last couple of comments are included in the 2.4.3.2 update I merged a couple of days ago.
