### ISSUE TITLE
Send report by mail

### ISSUE THREAD

**Issue by Turtle-Sec** [Tripwire/tripwire-open-source#33]
Hi, I search to send my report by mail, but i don't find anywhere  good informations.
I have to the report via a service account (that take an authentification) via SMTP to send email on my personnal address mail
So, can you help me please ? :)

**Comment by brc0x1** [comment]
Ok, the builtin SMTP client in OST is fairly basic, so if you need to use authentication, TLS, or other SMTP extensions, you'll need to set MAILMETHOD=SENDMAIL instead.  We could probably use a better name than "SENDMAIL" for this feature, because this mail method pipes the email to the child process specified in the MAILPROGRAM config file option, and that child process doesn't have to be sendmail.  Here's a very thorough article I ran across with a bunch of email tools you might be able to use: https://blog.edmdesigner.com/send-email-from-linux-command-line/ .  Note that you can include command line args in your MAILPROGRAM value if you need them; a very common value for this field is "/usr/sbin/sendmail -oi -t".

One other thing to be aware of is that the From: address defaults to "tripwire@[hostname]".  If you want to set it to something else, you can do that with the MAILFROMADDRESS config file option

**Comment by Turtle-Sec** [comment]
Okay thangs :)

**Comment by brc0x1** [comment]
Closing as resolved.
