### ISSUE TITLE
Issue with ecryptfs?

### ISSUE THREAD

**Issue by tenflo** [Tripwire/tripwire-open-source#38]
Hi,

Sometimes tripwire detects some modifications on all files of my ecryptfs partition:
[...]
-------------------------------------------------------------------------------
Rule Name: Security Control (/home/tenflo/.ssh)
Severity Level: 66
-------------------------------------------------------------------------------

Modified:
"/home/tenflo/.ssh"
"/home/tenflo/.ssh/authorized_keys"
[...]
mount | grep home
/home/.ecryptfs/tenflo/.Private on /home/tenflo type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=1048531b9e8064b3,ecryptfs_sig=1167f0335614ee57,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)

Whereas the sha512sum of my files don't change. Why tripwire detects a modification in this case?

**Comment by brc0x1** [comment]
Hi tenflo, my first guess would be that you're encountering a change to file metadata rather than contents, possibly one or more of the file timestamps.  I see the volume's mounted with 'relatime' rather than 'noatime' so it's possible that the file access times are getting bumped up when some program reads those files.

Could you do a <tt>twprint -m r -t 4</tt> on a report file containing these changes, & post a snippet?  That will show what changed about these files, & it ought to give us some clues about what's going on.  I've never actually used eCryptFS, and I'm curious to see if there's something around file metadata that it handles differently than non-encrypting filesystems.

**Comment by tenflo** [comment]
It seems to be the device number that is changing:

sudo twprint -m r -t 4 -r tenflo-silencio-20190316-075829.twr
[...]
Modified object name:  /home/tenflo/.ssh/authorized_keys

  Property:            Expected                    Observed                    
  -------------        -----------                 -----------                 
  Object Type          Regular File                Regular File                
* Device Number        55                          54                          
  File Device Number   0                           0                           
  Inode Number         44957802                    44957802                    
  Mode                 -rw-rw-r--                  -rw-rw-r--                  
  Num Links            1                           1                           
  UID                  tenflo (1000)               tenflo (1000)               
  GID                  tenflo (1000)               tenflo (1000)               
  Size                 820                         820                         
  Modify Time          Fri May 16 18:15:41 2014    Fri May 16 18:15:41 2014    
  Change Time          Sun Nov 29 10:00:07 2015    Sun Nov 29 10:00:07 2015    
  Blocks               24                          24                          
  CRC32                ARKZ3p                      ARKZ3p                      
  MD5                  Bj4Lxxvtj5GSm9a/+yYnvI      Bj4Lxxvtj5GSm9a/+yYnvI
[...]

**Comment by brc0x1** [comment]
Ok, I suspect what's happening here is that the ecryptfs filesystem layer is being dynamically assigned a new device number on remount or reboot.  I did a quick search & ran across a couple of [other](https://www.linuxquestions.org/questions/linux-security-4/tripwire-reports-that-all-my-files-had-the-device-number-modified-564263/) [examples](https://forums.gentoo.org/viewtopic-p-8270792.html?sid=696c2ca86af07beb9a41884d50890b45) of people running into this situation with other types of devices.  If this is what's going on, it's probably going to continue changing every so often.  You have a couple of options if you aren't interested in seeing these changes.

- Update your tripwire policy to not monitor device numbers.  To do this, you'd want to figure out which of your start points are at or below your ecryptfs mount point, and exclude 'd' from those.  Suppose (for example) your ecryptfs covered your whole home directory, and you had a couple of start points inside it, 
```
/home/tenflo/secret_files -> $(IgnoreNone);
/home/tenflo/more_secret_files -> +pinugtd;
```
You could change these to 
```
/home/tenflo/secret_files -> $(IgnoreNone) -d;
/home/tenflo/more_secret_files -> +pinugt;
```
...and that would prevent future checks from reporting on device number changes for these directories.

- If you'd rather not stop monitoring device numbers, apparently there is some way to configure udev or devtmpfs so that ecryptfs always gets the same device number, which would prevent this change from happening in the first place.  I've never actually tried this & I don't know how to set it up, but I thought I should pass it along as another option.

For the sake of being extra paranoid, you might take a quick look at your mounts and verify there isn't anything else mounted over top of your expected ecryptfs mount.  That's probably not what's going on here, but it only takes a minute to check.

**Comment by tenflo** [comment]
Cool, I no longer have this issue with the -d
