### ISSUE TITLE
Compilation with static libraries fails

### ISSUE THREAD

**Issue by EChauve** [Tripwire/tripwire-open-source#40]
Hi,

I am trying to make an a portable version of the Tripwire agent.
But `configure` fails with the `--enable-static` option. 
These are the last lines of its output :
```
checking for pthread_getspecific... no
checking for pthread_getspecific... no
checking for pthread_getspecific... no
configure: error: No posix threads detected, cannot continue.
```

I am guessing a library must be missing but I can't identify which one. 
I am working on RHEL 7.6, glibc-static and glibc are installed and up-to-date.

Thank you for any guidance you can provide.

**Comment by brc0x1** [comment]
Hmm.  That's odd.  The check for pthread_getspecific() _should_ only happen if the configure script thinks the compiler doesn't provide a full STL implementation ( see https://github.com/Tripwire/tripwire-open-source/blob/master/configure.ac#L272-L288 ), so this should only happen with a really ancient OS/compiler, or maybe if the gcc-c++ package isn't installed (I'm not sure I've ever tried that).  I'll have to spin up a 7.6 vm and see if I can repro this.  Just to be sure I've got the same setup, are you using the usual gcc, glibc, & glibc-static from yum, or something else?

**Comment by EChauve** [comment]
These are the packages installed on the server :
- gcc-4.8.5-36.el7_6.1.x86_64
- glibc-2.17-260.el7_6.3.x86_64
- glibc-static-2.17-260.el7_6.3.x86_64
- gcc-c++-4.8.5-36.el7_6.1.x86_64

They were all installed with yum from the company's repository.

**Comment by EChauve** [comment]
Can the missing library (if it is the correct explanation for the problem encountered) be installed but not found because of an environnement variable with a missing/wrong value?

Maybe I could side-step the issue and build a portable package another way? Do you have any sugggestions, or documentation you could refer me to?

My aim is to build a portable package able to install the Tripwire agent in a custom directory, with all related files owned by a "tripwire" user (with required sudoers privileges).
We use a custom package format and installer that allow the execution of an installation script (BASH) by the root user. So we should have plenty of options.

**Comment by brc0x1** [comment]
Ok, I think I figured out what's going on.  I repro'd the build failure on a CentOS 7.6 vm with the listed packages, then installed the additional package **libstdc++-static** with yum, and after that it built successfully, and all tests passed.  So that ought to sort out your immediate problem, although the [usual caveats about glibc and static linking](https://www.systutorials.com/5217/how-to-statically-link-c-and-c-programs-on-linux-with-gcc/) definitely apply.  In particular, uid/gid to name lookups can blow up if glibc needs to load a shared library behind the scenes to resolve the name, as happens with NIS or LDAP users & groups.  If you encounter this and you need to use static binaries, you might need to set "RESOLVE_IDS_TO_NAMES=false" in your tw.cfg file.  Static binaries built with simpler libcs like Musl (as on Alpine Linux) don't have this problem, but I don't think I've ever tried running one of those on a RHEL-based distro so I can't speak to how portable that approach would actually be.

If static binaries aren't a requirement, another approach would be to just do dynamic builds, building on the oldest OS (and thus compiler+glibc) you plan on supporting.

As for setup, you might want to look at the install.sh script in the installer folder.  It's used for "make install" specifically, but it walks the user through a number of steps like generating keys, setting up various config options, and creating a default policy, so those parts are things you might want to adapt for your custom installer.

**Comment by EChauve** [comment]
Thank you very much. **libstdc++-static** was indeed the library I was missing.
The install.sh was useful and saved me a lot of time.

I couldn't complete the static compilation for Solaris 10 (next part of my project) though I realize it was to be expected (there is a warning on that subject in the README.txt file).

Again, thank you for your time.
