### ISSUE TITLE
Tripwire build problem

### ISSUE THREAD

**Issue by memrekaraaslan** [Tripwire/tripwire-open-source#43]
Hello

I am making some changes to the source code and trying to generate a binary file again. But I cannot achieve this. I tried with "make" and "make install", but no changes were made.

How should I use which commands to recompile and run the existing project on the machine ?

Thank you.

**Comment by brc0x1** [comment]
Hi there, let me see if I understand the problem you're having.  You have already built OST successfully, and now you're trying to make some changes and your binaries aren't getting rebuilt?  Would that be an accurate description?  If that's what's going on, I think this is caused by some file timestamps being out of sync; the simplest thing to do in this case would be to just do a 'make clean' and rebuild.  If that takes too long, you could try just deleting the existing binaries and .a files in the lib directory, and then run 'make'.

If what I described above is _not_ the problem you're having, could you provide a bit more detail on what you see when you run a 'make' or 'make install'?  That might give me some better clues about what's going on.

Thanks,
-b

**Comment by brc0x1** [comment]
Inactive for > 1 year, closing.
