### ISSUE TITLE
Windows Compilation,

### ISSUE THREAD

**Issue by rickespana** [Tripwire/tripwire-open-source#47]
has anyone tried to build triwire on windows?

**Comment by brc0x1** [comment]
Hi rickespana, sorry about the delayed reply.  Unfortunately OST is very POSIX-centric and doesn't have native Windows support.  You have a couple of options here:
* Tripwire for Servers is OST's commercial, non-open-source sibling, available through tripwire.com.  It supports Win32 file attribute bits, ACLs, alternate data streams etc., and can also scan registry keys/values, and can associate security log events with changes to figure out who changed something.  It also has an optional management console if you need to manage it across a lot of machines.  Plus dedicated support people who, uh, get back to you in a more timely fashion than I just did.  :)  
* OST is known to work with either Cygwin or DJGPP, since those provide a sort of POSIX-like layer on top of the real filesystem.  You don't get all the native stuff I mentioned above, but if you only really care about hashes changing one of these options might do the job for you.
* I'm not sure this really counts as building on Windows, but running Linux binaries via WSL also works, albeit with the same caveats as for Cygwin etc.

-b

**Comment by brc0x1** [comment]
Closing as an inactive issue.
