### ISSUE TITLE
Compile issue on fedora 24

### ISSUE THREAD

**Issue by didier13150** [Tripwire/tripwire-open-source#8]
`policy.y:221:1: error: narrowing conversion of '65535' from 'int' to 'short int' inside { } [-Wnarrowing]`
Complete issue can be found here: [https://bugzilla.redhat.com/attachment.cgi?id=1126647](url)

**Comment by brc0x1** [comment]
This is being fixed in OST 2.4.3.1.  See pull request: https://github.com/Tripwire/tripwire-open-source/pull/9

**Comment by brc0x1** [comment]
Btw I'm going to verify that OST builds & runs correctly on Fedora 24 before merging this update.

**Comment by didier13150** [comment]
good news. thanks

**Comment by brc0x1** [comment]
Ok, the 2.4.3.1 update is out.  GCC 6 support is the main new thing, along with fixing warnings and general code cleanup.  With GCC 6 you'll see a fair number of warnings about std::auto_ptr being deprecated; this is harmless for now, but I'd like to address it in a future update, if I can figure out how to use std::unique_ptr when the compiler offers it, and std::auto_ptr otherwise.

**Comment by didier13150** [comment]
Confirmed. You can close this bug if you want. Thanks a lot.
